online-store_with_flask/product/models.py
PRODUCTS = {
    'iphone': {
        'name': 'iPhone 5S',
        'category': 'Phones',
        'price': 699,
    },
    'galaxy': {
        'name': 'Samsung Galaxy 5',
        'category': 'Phones',
        'price': 649,
    },
    'ipad-air': {
        'name': 'iPad Air',
        'category': 'Tablets',
        'price': 649,
    },
    'ipad-mini': {
        'name': 'iPad Mini',
        'category': 'Tablets',
        'price': 549
    }
}

online-store_with_flask/app.py
from flask import Flask, render_template, request
from product.views import product_blueprint
import ccy

app = Flask(__name__)
app.register_blueprint(product_blueprint)


@app.route('/')
@app.route('/hello')
def hello_world():
    user = request.args.get('user', 'Shamil')
    return render_template('index.html', user=user)


@app.template_filter('format_currency')
def format_currency_filter(amount):
    currency_code = ccy.countryccy(request.accept_languages.best[-2:])
    return '{0} {1}'.format(currency_code, amount)



if __name__ == '__main__':
    app.run(debug=True)

online-store_with_flask/product/views.py
from werkzeug.exceptions import abort
from flask import render_template
from flask import Blueprint
from product.models import PRODUCTS

product_blueprint = Blueprint('product', __name__)


@product_blueprint.route('/')
@product_blueprint.route('/home')
def home():
    return render_template('home.html', products=PRODUCTS)


@product_blueprint.route('/product/<key>')
def product(key):
    product = PRODUCTS.get(key)
    if not product:
        abort(404)
    return render_template('product.html', product=product)


@product_blueprint.app_template_filter('full_name')
def full_name_filter(product):
    return '{0} / {1}'.format(product['category'], product['name'])


@product_blueprint.context_processor
def some_processor():
    def full_name(product):
        return '{0} / {1}'.format(product['category'],product['name'])
    return {'full_name': full_name}

online-store_with_flask/templates/_helpers.html
{% macro render_field(name, class='', value='', type='text') -%}

<label>
    <input type="{{ type }}" name="{{ name }}" class="{{ class }}" value="{{ value }}"/>
</label>

{%- endmacro %}

online-store_with_flask/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Framework</title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    <script src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
 </head>
 <body>
 <div class="container">
     <div class="navbar-header">
         <a class="navbar-brand" href="{{ url_for('product.home') }}">Home</a>
     </div>
 </div>
 <div class="container">
 {% block container %}{% endblock %}
 </div>
 <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
 <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
 </body>
</html>

online-store_with_flask/templates/home.html
{% extends 'base.html' %}

{% block container %}
 <div class="top-pad">
 {% for id, product in products.items() %}
 <div class="top-pad offset-1 col-sm-10">
 <div class="card text-center">
     <h2>
         <a href="{{ url_for('product.product', key=id)
                 }}">{{ product['name'] }}</a>
         <small>$ {{ product['price'] }}</small>
     </h2>

     {% from '_helpers.html' import render_field %}
<!--
<fieldset>
{{ render_field('username', 'icon-user') }}
{{ render_field('password', 'icon-key', type='password') }}
</fieldset>
-->

 </div>
 </div>
 {% endfor %}
 </div>
{% endblock %}

online-store_with_flask/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask Framework</title>
</head>
<body>
    <h1>Hello {{ user }}!</h1>
    <p>Welcome to the world of Flask!</p>
</body>
</html>

online-store_with_flask/templates/product.html
{% extends 'home.html' %}
{% block container %}
 <div class="top-pad">
 <h4>{{ product|full_name }}</h4>
 <h1>{{ product['name'] }}</h1>
 <h3><small>{{ product['category'] }}</small></h3>
 <h5>$ {{ product['price'] }}</h5>
 <h3>{{ product['price']|format_currency }}</h3>
 </div>
{% endblock %}